### PR TITLE
Add posterior values to output of get_tidy_oxcalresult(). Fixes #32

### LINKED ISSUE #32: get_tidy_oxcalresult() doesn't read posteriors
#17 added support for posterior values (sigma ranges and raw probabilities) to `parseOxcalOutput()` and the plotting functions, but `get_tidy_oxcalresult()` seems to have been missed.

### PR DESCRIPTION
**Pull request by joeroe**
Adds getter functions for `posterior_sigma_range` and `posterior_probabilities` elements of an `oxcAARCalibratedDates` or `oxcAARCalibratedDatesList` object; adds those to `get_tidy_oxcalresult()`; and updates documentation accordingly.

### CODE REVIEW

**Comment by MartinHinz** [comment]
Thank you very much, most appreciated! That travis fails is kind of strange for me... But is also the case in master. I might have to fix that in master, and than you can probably base your pull request on the fixed master again?

**Comment by joeroe** [comment]
I noticed after making the pull request that `test_tidy_ouput` was failing (still new to testing!) so I've added a commit to fix that. But yes not sure about the failure to build `basic-usage.Rmd`... I haven't touched it, and it builds on my machine.

**Comment by MartinHinz** [comment]
It is failing now due to system requirements. I try to force travis to a newer ubuntu version, than it will hopefully run. Somewhen during the day... Now I have to teach students for 2 h

**Comment by MartinHinz** [comment]
It turns out that the newer version of Oxcal is compiled with glibc 2.29, that is not available for the bionic ubuntu that seem to be the last version travis ships with R language. Since it is cross compilation, I have to 'deliver' that environment. I am on it.

**Comment by joeroe** [comment]
Hi @MartinHinz. I looked into this a bit since it's also causing [stratigraphr](https://github.com/joeroe/stratigraphr) to fail on Travis, and I think the problem is that v2.29 isn't available on *any* version of Ubuntu (https://pkgs.org/download/libc6). This honestly seems like more of a problem with OxCal/Ubuntu, than your package :)

I got around it by switching from Travis to GitHub Actions, as recommended here: https://www.tidyverse.org/blog/2020/04/usethis-1-6-0/

**Comment by MartinHinz** [comment]
Thank you so much! As I was expecting it. I just added a branch 'github_action' testing this, and if successful, I will merge this with master switching the testing environment. Keep you posted!

**Comment by MartinHinz** [comment]
I just switched in master to github actions, thank you very much for suggesting this. Would you like to rebase your PR on the new master? It is not strictly necessary, but it would probably more clean to go this way?

**Comment by joeroe** [comment]
Sure, done.

**Comment by MartinHinz** [comment]
Thanks alot! Merged.

**Pull request merged**
