### PR TITLE
Dev parse modeled dates

### PR DESCRIPTION
**Pull request by MartinHinz**
posterior probabilities are now parsed from OxCal output file and printed via format rsp. plotted in individual and list plots

### CODE REVIEW

**Comment by nevrome** [comment]
That's a very nice feature. But shouldn't the posterior probabilities output be more like the one you prepared for c14bazAAR?  

```
library(magrittr)
library(c14bazAAR)

get_aDRAC() %>% calibrate() %$% calrange %>% magrittr::extract2(1)
```

|dens|from|to
|---|---|---|
58.2|2325|2490
2.5|2603|2606
33.2|2643|2676

It's nice to know the full range, but it's also misleading.

**Comment by MartinHinz** [comment]
Thank you for the valuable remark! Does 8065ae9e81a038e1ee16e47bbae9192d77e63c41 format the date as needed?

**Comment by nevrome** [comment]
Nice! But it breaks the plot. What about this (c5cffa209330101a63ef6364cd4f20eda1ed58fd) solution? Not perfect, but at least without overlaps.

**Comment by MartinHinz** [comment]
Thank you, @nevrome, did some improvement (?) yesterday on the plane, so I merged yours proposal partly in. Now plots should work and look much better.

**Comment by nevrome** [comment]
Unfortunately something is broken now. This code from the vignette doesn't work anymore:

```
my_sum_sim<-oxcalSumSim(
  timeframe_begin = -4000,
  timeframe_end = -3000,
  n = 50,
  stds = 35,
  date_distribution = "uniform"
  )
str(my_sum_sim)
plot(my_sum_sim)
```

I guess you can solve this much faster than I can.

**Comment by MartinHinz** [comment]
This time checked and tested, no errors, notes or warnings. Should have done that, of course, in the first place.

**Pull request merged**
